export const checks: Check[] = [ 
{month: 1, text: ['Lifts head when on his tummy',
'Responds to sound',
'Stares at faces',
'Turns head towards light',
'Can see black-and-white patterns',
'Follows objects',
'Makes "ooh" and "ah" sounds',
'Smiles',
'Holds head at 45-degree angle'
]},
{month: 2, text: ['Makes gurgling and cooing sounds',
'Follows faces and objects when held near face',
'Holds head up for short periods',
'Recognises your voice',
'Smiles responsively',
'Holds head at 45-degree angle',
'Movements become smoother',
'Holds head steady',
'Bears weight on legs',
'May lift head and shoulders (mini push-up)']}, 
{month: 3, text: ['Holds head steady',
'Recognises your face',
'Does mini push-ups',
'Laughs and smiles',
'Turns towards loud sounds',
'May bring hands together and bat at toys'
]},
{month: 4, text: ['Holds head up steadily',
'Can bear weight on legs',
'Coos when you talk to him',
'Does mini push-ups',
'Can reach out and grasp objects or toys',
'Imitates speech sounds, such as "baba" and "dada"',
'May cut first tooth',
'May roll over from tummy to back']},
{month: 5, text: ['Can distinguish between bold colours',
'Can roll over from tummy to back',
'Amuses himself by playing with hands and feet',
'Turns towards new sounds',
'May sit momentarily without support',
'May roll over from back to tummy',
'Mouths objects',
'May show signs of stranger anxiety']},
{month: 6, text: ['Turns towards sounds and voices',
'Imitates sounds, blows bubbles',
'Ready for solid foods',
'Reaches for objects and mouths them',
'Rolls in both directions',
'Recognises own name',
'May lunge forward or start crawling',
'May jabber or combine syllables',
'May drag object towards himself',
'May sit without support']},
{month: 7, text: ['Reaches for things with a sweeping motion',
'Imitates speech sounds (babbles)',
'Combines syllables into word-like sounds',
'Begins to crawl or lunges forward',
'Picks up objects with one hand and passes to the other hand',
'Bangs objects together',
'Sits without support',
'Stands while holding onto something',
'Waves goodbye']},
{month: 8, text: ['Sits without support',
'Says "dada" and "mama" to both parents (isnt specific)',
'Begins to crawl',
'Passes object from hand to hand',
'Stands while holding on to something',
'Crawls well',
'Pulls self to standing position, cruises around furniture while holding on',
'Picks things up with thumb-and-finger pincer grasp',
'Indicates wants with gestures']},
{month: 9, text: ['Combines syllables into word-like sounds',
'Pulls self to standing and sitting positions',
'Bangs, drops, and throws objects',
'Tries to grasp spoon when being fed',
'Uses pincer grasp to pick up objects',
'Cruises while holding on to furniture',
'Plays pat-a-cake and peek-a-boo',
'Says "dada" and "mama" to the right parent (is specific)']},
{month: 10, text: ['Picks things up with pincer grasp',
'Crawls well',
'Cruises',
'Says "dada" and "mama" to the right parent (is specific)',
'Points at distant objects',
'Responds to name and understands "no"',
'Indicates wants with gestures',
'Drinks from a cup',
'Stands alone for a couple of seconds',
'Puts objects into a container']},
{month: 11, text: ['Says "dada" and "mama" to the right parent (is specific)',
'Plays pat-a-cake',
'Points at objects',
'Imitates others activities',
'Puts objects into a container',
'Understands simple instructions',
'Stands alone for a couple of seconds',
'Says one word besides "mama" and "dada"',
'Stoops from standing position',
'Takes a few steps']},
{month: 12, text: ['Imitates others activities',
'Jabbers word-like sounds',
'Points, waves goodbye and claps',
'Says one word besides "mama" and "dada"',
'Takes a few steps or bum-shuffles',
'Understands and responds to simple instructions, such as "Come here"',
'Once shown, can put objects inside a container and take them out again',
'Scribbles with crayon',
'Walks well',
'Says two words besides "mama" and "dada"',
'Understands some words, such as "drink", "car" or "ball"'
]},];